replicas: 1

image:
  name: linuxserver/radarr
  tag: latest

storage:
  config:
    enabled: true
    size: 5Gi
    path: /config

mounts: []
#  - pvcName: ""
#    mountName: ""
#    path: ""

resources:
  limits:
    memory: 2Gi
    cpu: 4
  requests:
    memory: 128Mi
    cpu: 200m

ports:
  webui: 7878
envVars: []
resources:
  limits:
    memory: 2048Mi
    cpu: 1
  requests:
    memory: 1024Mi
    cpu: 250m
