apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" .Release.Name }}
  namespace: {{ .Release.Namespace | or .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.ports.webui }}
    targetPort: {{ .Values.ports.webui }}
  type: LoadBalancer
